AMENITY_MAPPING = {
    "restaurant": "amenity=restaurant",
    "restaurants": "amenity=restaurant",
    "park": "leisure=park",
    "parks": "leisure=park",
    "school": "amenity=school",
    "schools": "amenity=school",
    "hospital": "amenity=hospital",
    "hospitals": "amenity=hospital",
    "cafe": "amenity=cafe",
    "cafes": "amenity=cafe",
    "bar": "amenity=bar",
    "bars": "amenity=bar",
    "pub": "amenity=pub",
    "pubs": "amenity=pub",
    "hotel": "tourism=hotel",
    "hotels": "tourism=hotel",
    "bank": "amenity=bank",
    "banks": "amenity=bank",
    "supermarket": "shop=supermarket",
    "supermarkets": "shop=supermarket",
    "pharmacy": "amenity=pharmacy",
    "pharmacies": "amenity=pharmacy",
    "cinema": "amenity=cinema",
    "cinemas": "amenity=cinema",
    "library": "amenity=library",
    "libraries": "amenity=library",
    "police": "amenity=police",
    "fire station": "amenity=fire_station",
    "post office": "amenity=post_office",
    "place of worship": "amenity=place_of_worship",
    "places of worship": "amenity=place_of_worship",
    "bus stop": "highway=bus_stop",
    "bus stops": "highway=bus_stop",
    "train station": "railway=station",
    "train stations": "railway=station",
    "airport": "aeroway=aerodrome",
    "airports": "aeroway=aerodrome",
    "fuel": "amenity=fuel",
    "gas station": "amenity=fuel",
    "gas stations": "amenity=fuel",
    "parking": "amenity=parking",
    "atm": "amenity=atm",
    "atms": "amenity=atm",
    "fast food": "amenity=fast_food",
    "doctors": "amenity=doctors",
    "dentist": "amenity=dentist",
    "veterinary": "amenity=veterinary",
    "theatre": "amenity=theatre",
    "theatres": "amenity=theatre",
    "nightclub": "amenity=nightclub",
    "nightclubs": "amenity=nightclub",
    "community centre": "amenity=community_centre",
    "community centres": "amenity=community_centre",
    "social facility": "amenity=social_facility",
    "social facilities": "amenity=social_facility",
    "marketplace": "amenity=marketplace",
    "marketplaces": "amenity=marketplace",
    "recycling": "amenity=recycling",
    "toilets": "amenity=toilets",
    "bench": "amenity=bench",
    "benches": "amenity=bench",
    "drinking water": "amenity=drinking_water",
    "fountain": "amenity=fountain",
    "fountains": "amenity=fountain",
    "shelter": "amenity=shelter",
    "shelters": "amenity=shelter",
    "telephone": "amenity=telephone",
    "telephones": "amenity=telephone",
    "waste basket": "amenity=waste_basket",
    "waste baskets": "amenity=waste_basket",
    "waste disposal": "amenity=waste_disposal",
    "public bath": "amenity=public_bath",
    "public baths": "amenity=public_bath",
    "refugee site": "amenity=refugee_site",
    "refugee sites": "amenity=refugee_site",
    "vending machine": "amenity=vending_machine",
    "vending machines": "amenity=vending_machine",
    "animal boarding": "amenity=animal_boarding",
    "animal breedings": "amenity=animal_breeding",
    "animal shelter": "amenity=animal_shelter",
    "animal shelters": "amenity=animal_shelter",
    "arts centre": "amenity=arts_centre",
    "arts centres": "amenity=arts_centre",
    "bbq": "amenity=bbq",
    "bicycle parking": "amenity=bicycle_parking",
    "bicycle rental": "amenity=bicycle_rental",
    "bicycle repair station": "amenity=bicycle_repair_station",
    "bicycle repair stations": "amenity=bicycle_repair_station",
    "boat rental": "amenity=boat_rental",
    "boat sharing": "amenity=boat_sharing",
    "boat storage": "amenity=boat_storage",
    "bureau de change": "amenity=bureau_de_change",
    "bus station": "amenity=bus_station",
    "bus stations": "amenity=bus_station",
    "car rental": "amenity=car_rental",
    "car sharing": "amenity=car_sharing",
    "car wash": "amenity=car_wash",
    "casino": "amenity=casino",
    "casinos": "amenity=casino",
    "charging station": "amenity=charging_station",
    "charging stations": "amenity=charging_station",
    "childcare": "amenity=childcare",
    "clinic": "amenity=clinic",
    "clinics": "amenity=clinic",
    "clock": "amenity=clock",
    "clocks": "amenity=clock",
    "college": "amenity=college",
    "colleges": "amenity=college",
    "compressed air": "amenity=compressed_air",
    "courthouse": "amenity=courthouse",
    "courthouses": "amenity=courthouse",
    "crematorium": "amenity=crematorium",
    "crematoria": "amenity=crematorium",
    "dive centre": "amenity=dive_centre",
    "dive centres": "amenity=dive_centre",
    "dog toilet": "amenity=dog_toilet",
    "dog toilets": "amenity=dog_toilet",
    "driving school": "amenity=driving_school",
    "driving schools": "amenity=driving_school",
    "embassy": "office=diplomatic",
    "embassies": "office=diplomatic",
    "ferry terminal": "amenity=ferry_terminal",
    "ferry terminals": "amenity=ferry_terminal",
    "food court": "amenity=food_court",
    "food courts": "amenity=food_court",
    "funeral hall": "amenity=funeral_hall",
    "funeral halls": "amenity=funeral_hall",
    "gambling": "amenity=gambling",
    "game feeding": "amenity=game_feeding",
    "grave yard": "amenity=grave_yard",
    "grave yards": "amenity=grave_yard",
    "grit bin": "amenity=grit_bin",
    "grit bins": "amenity=grit_bin",
    "hunting stand": "amenity=hunting_stand",
    "hunting stands": "amenity=hunting_stand",
    "ice cream": "amenity=ice_cream",
    "internet cafe": "amenity=internet_cafe",
    "internet cafes": "amenity=internet_cafe",
    "kindergarten": "amenity=kindergarten",
    "kindergartens": "amenity=kindergarten",
    "kitchen": "amenity=kitchen",
    "kitchens": "amenity=kitchen",
    "language school": "amenity=language_school",
    "language schools": "amenity=language_school",
    "loading dock": "amenity=loading_dock",
    "loading docks": "amenity=loading_dock",
    "lounger": "amenity=lounger",
    "loungers": "amenity=lounger",
    "money transfer": "amenity=money_transfer",
    "motorcycle parking": "amenity=motorcycle_parking",
    "music school": "amenity=music_school",
    "music schools": "amenity=music_school",
    "nursing home": "amenity=nursing_home",
    "nursing homes": "amenity=nursing_home",
    "parking entrance": "amenity=parking_entrance",
    "parking entrances": "amenity=parking_entrance",
    "parking space": "amenity=parking_space",
    "parking spaces": "amenity=parking_space",
    "payment centre": "amenity=payment_centre",
    "payment centres": "amenity=payment_centre",
    "payment terminal": "amenity=payment_terminal",
    "payment terminals": "amenity=payment_terminal",
    "photo booth": "amenity=photo_booth",
    "photo booths": "amenity=photo_booth",
    "place of mourning": "amenity=place_of_mourning",
    "places of mourning": "amenity=place_of_mourning",
    "post box": "amenity=post_box",
    "post boxes": "amenity=post_box",
    "post depot": "amenity=post_depot",
    "post depots": "amenity=post_depot",
    "prison": "amenity=prison",
    "prisons": "amenity=prison",
    "public bookcase": "amenity=public_bookcase",
    "public bookcases": "amenity=public_bookcase",
    "ranger station": "amenity=ranger_station",
    "ranger stations": "amenity=ranger_station",
    "recycling centre": "amenity=recycling_centre",
    "recycling centres": "amenity=recycling_centre",
    "sanitary dump station": "amenity=sanitary_dump_station",
    "sanitary dump stations": "amenity=sanitary_dump_station",
    "shower": "amenity=shower",
    "showers": "amenity=shower",
    "ski rental": "amenity=ski_rental",
    "ski school": "amenity=ski_school",
    "ski schools": "amenity=ski_school",
    "social centre": "amenity=social_centre",
    "social centres": "amenity=social_centre",
    "studio": "amenity=studio",
    "studios": "amenity=studio",
    "surf school": "amenity=surf_school",
    "surf schools": "amenity=surf_school",
    "taxi": "amenity=taxi",
    "taxis": "amenity=taxi",
    "tools library": "amenity=tools_library",
    "tools libraries": "amenity=tools_library",
    "townhall": "amenity=townhall",
    "townhalls": "amenity=townhall",
    "toy library": "amenity=toy_library",
    "toy libraries": "amenity=toy_library",
    "training": "amenity=training",
    "training centre": "amenity=training",
    "training centres": "amenity=training",
    "university": "amenity=university",
    "universities": "amenity=university",
    "vacuum cleaner": "amenity=vacuum_cleaner",
    "vacuum cleaners": "amenity=vacuum_cleaner",
    "vehicle inspection": "amenity=vehicle_inspection",
    "vehicle inspections": "amenity=vehicle_inspection",
    "waste transfer station": "amenity=waste_transfer_station",
    "waste transfer stations": "amenity=waste_transfer_station",
    "water point": "amenity=water_point",
    "water points": "amenity=water_point",
    "watering place": "amenity=watering_place",
    "watering places": "amenity=watering_place",
    "events venue": "amenity=events_venue",
    "events venues": "amenity=events_venue",
    "parcel locker": "amenity=parcel_locker",
    "parcel lockers": "amenity=parcel_locker",
    "monastery": "amenity=monastery",
    "monasteries": "amenity=monastery",
    "mobile money agent": "amenity=mobile_money_agent",
    "mobile money agents": "amenity=mobile_money_agent",
    "ticket validator": "amenity=ticket_validator",
    "ticket validators": "amenity=ticket_validator",
    "weighbridge": "amenity=weighbridge",
    "weighbridges": "amenity=weighbridge",
    "lavoir": "amenity=lavoir",
    "lavoirs": "amenity=lavoir",
    "biergarten": "amenity=biergarten",
    "biergartens": "amenity=biergarten",
    "prep school": "amenity=prep_school",
    "prep schools": "amenity=prep_school",
    # Leisure tags
    "playground": "leisure=playground",
    "playgrounds": "leisure=playground",
    "sports centre": "leisure=sports_centre",
    "sports centres": "leisure=sports_centre",
    "stadium": "leisure=stadium",
    "stadiums": "leisure=stadium",
    "pitch": "leisure=pitch",
    "pitches": "leisure=pitch",
    "track": "leisure=track",
    "tracks": "leisure=track",
    "swimming pool": "leisure=swimming_pool",
    "swimming pools": "leisure=swimming_pool",
    "golf course": "leisure=golf_course",
    "golf courses": "leisure=golf_course",
    "ice rink": "leisure=ice_rink",
    "ice rinks": "leisure=ice_rink",
    "fitness centre": "leisure=fitness_centre",
    "fitness centres": "leisure=fitness_centre",
    "garden": "leisure=garden",
    "gardens": "leisure=garden",
    "dog park": "leisure=dog_park",
    "dog parks": "leisure=dog_park",
    "nature reserve": "leisure=nature_reserve",
    "nature reserves": "leisure=nature_reserve",
    "picnic site": "leisure=picnic_site",
    "picnic sites": "leisure=picnic_site",
    "beach resort": "leisure=beach_resort",
    "beach resorts": "leisure=beach_resort",
    "marina": "leisure=marina",
    "marinas": "leisure=marina",
    "water park": "leisure=water_park",
    "water parks": "leisure=water_park",
    "fishing": "leisure=fishing",
    "common": "leisure=common",
    # Shop tags
    "bakery": "shop=bakery",
    "bakeries": "shop=bakery",
    "butcher": "shop=butcher",
    "butchers": "shop=butcher",
    "clothes": "shop=clothes",
    "convenience": "shop=convenience",
    "department store": "shop=department_store",
    "department stores": "shop=department_store",
    "electronics": "shop=electronics",
    "florist": "shop=florist",
    "florists": "shop=florist",
    "furniture": "shop=furniture",
    "gift": "shop=gift",
    "gifts": "shop=gift",
    "hairdresser": "shop=hairdresser",
    "hairdressers": "shop=hairdresser",
    "hardware": "shop=hardware",
    "jewelry": "shop=jewelry",
    "kiosk": "shop=kiosk",
    "kiosks": "shop=kiosk",
    "laundry": "shop=laundry",
    "mall": "shop=mall",
    "malls": "shop=mall",
    "optician": "shop=optician",
    "opticians": "shop=optician",
    "pet": "shop=pet",
    "pet store": "shop=pet",
    "pet stores": "shop=pet",
    "shoes": "shop=shoes",
    "sports": "shop=sports",
    "sports shop": "shop=sports",
    "sports shops": "shop=sports",
    "stationery": "shop=stationery",
    "travel agency": "shop=travel_agency",
    "travel agencies": "shop=travel_agency",
    "book": "shop=books",
    "books": "shop=books",
    "music": "shop=music",
    "toys": "shop=toys",
    "car repair": "shop=car_repair",
    "car parts": "shop=car_parts",
    "bicycle": "shop=bicycle",
    "bicycle shop": "shop=bicycle",
    "bicycle shops": "shop=bicycle",
    # Tourism tags
    "museum": "tourism=museum",
    "museums": "tourism=museum",
    "gallery": "tourism=gallery",
    "galleries": "tourism=gallery",
    "zoo": "tourism=zoo",
    "zoos": "tourism=zoo",
    "theme park": "tourism=theme_park",
    "theme parks": "tourism=theme_park",
    "attraction": "tourism=attraction",
    "attractions": "tourism=attraction",
    "viewpoint": "tourism=viewpoint",
    "viewpoints": "tourism=viewpoint",
    "information": "tourism=information",
    "tourist information": "tourism=information",
    "artwork": "tourism=artwork",
    "artworks": "tourism=artwork",
    "guest house": "tourism=guest_house",
    "guest houses": "tourism=guest_house",
    "motel": "tourism=motel",
    "motels": "tourism=motel",
    "hostel": "tourism=hostel",
    "hostels": "tourism=hostel",
    "chalet": "tourism=chalet",
    "chalets": "tourism=chalet",
    "camp site": "tourism=camp_site",
    "camp sites": "tourism=camp_site",
    "caravan site": "tourism=caravan_site",
    "caravan sites": "tourism=caravan_site",
    "picnic table": "tourism=picnic_site",
    "picnic tables": "tourism=picnic_site",
    # Aeroway tags
    "aerodrome": "aeroway=aerodrome",
    "aerodromes": "aeroway=aerodrome",
    "runway": "aeroway=runway",
    "runways": "aeroway=runway",
    "taxiway": "aeroway=taxiway",
    "taxiways": "aeroway=taxiway",
    "helipad": "aeroway=helipad",
    "helipads": "aeroway=helipad",
    "heliport": "aeroway=heliport",
    "heliports": "aeroway=heliport",
    "apron": "aeroway=apron",
    "aprons": "aeroway=apron",
    "hangar": "aeroway=hangar",
    "hangars": "aeroway=hangar",
    "terminal": "aeroway=terminal",
    "terminals": "aeroway=terminal",
    "gate": "aeroway=gate",
    "gates": "aeroway=gate",
    "windsock": "aeroway=windsock",
    "windsocks": "aeroway=windsock",
    "airstrip": "aeroway=aerodrome",
    "airstrips": "aeroway=aerodrome",
    # Military tags
    "military base": "military=base",
    "military bases": "military=base",
    "barracks": "military=barracks",
    "training area": "military=training_area",
    "training areas": "military=training_area",
    "danger area": "military=danger_area",
    "danger areas": "military=danger_area",
    "range": "military=range",
    "ranges": "military=range",
    "naval base": "military=naval_base",
    "naval bases": "military=naval_base",
    "airfield": "military=airfield",
    "airfields": "military=airfield",
    "bunker": "military=bunker",
    "bunkers": "military=bunker",
    "checkpoint": "military=checkpoint",
    "checkpoints": "military=checkpoint",
    "nuclear explosion site": "military=nuclear_explosion_site",
    "nuclear explosion sites": "military=nuclear_explosion_site",
    "obstacle course": "military=obstacle_course",
    "obstacle courses": "military=obstacle_course",
    "office military": "military=office",
    "trench": "military=trench",
    "trenches": "military=trench",
    # Highway types (roads and paths)
    "motorway": "highway=motorway",
    "motorways": "highway=motorway",
    "trunk": "highway=trunk",
    "trunk road": "highway=trunk",
    "trunk roads": "highway=trunk",
    "primary road": "highway=primary",
    "primary roads": "highway=primary",
    "secondary road": "highway=secondary",
    "secondary roads": "highway=secondary",
    "tertiary road": "highway=tertiary",
    "tertiary roads": "highway=tertiary",
    "residential road": "highway=residential",
    "residential roads": "highway=residential",
    "residential street": "highway=residential",
    "residential streets": "highway=residential",
    "service road": "highway=service",
    "service roads": "highway=service",
    "track road": "highway=track",
    "track roads": "highway=track",
    "footway": "highway=footway",
    "footways": "highway=footway",
    "footpath": "highway=footway",
    "footpaths": "highway=footway",
    "path": "highway=path",
    "paths": "highway=path",
    "cycleway": "highway=cycleway",
    "cycleways": "highway=cycleway",
    "cycle path": "highway=cycleway",
    "cycle paths": "highway=cycleway",
    "bridleway": "highway=bridleway",
    "bridleways": "highway=bridleway",
    "pedestrian": "highway=pedestrian",
    "pedestrian zone": "highway=pedestrian",
    "pedestrian zones": "highway=pedestrian",
    "steps": "highway=steps",
    "stairs": "highway=steps",
    "crossing": "highway=crossing",
    "crossings": "highway=crossing",
    "pedestrian crossing": "highway=crossing",
    "pedestrian crossings": "highway=crossing",
    "traffic signals": "highway=traffic_signals",
    "traffic light": "highway=traffic_signals",
    "traffic lights": "highway=traffic_signals",
    "street lamp": "highway=street_lamp",
    "street lamps": "highway=street_lamp",
    "speed camera": "highway=speed_camera",
    "speed cameras": "highway=speed_camera",
    "mini roundabout": "highway=mini_roundabout",
    "mini roundabouts": "highway=mini_roundabout",
    "motorway junction": "highway=motorway_junction",
    "motorway junctions": "highway=motorway_junction",
    "turning circle": "highway=turning_circle",
    "turning circles": "highway=turning_circle",
    "rest area": "highway=rest_area",
    "rest areas": "highway=rest_area",
    "services": "highway=services",
    "motorway services": "highway=services",
    # Natural features (wildcard - matches all natural features)
    "natural": "natural=*",
    "natural feature": "natural=*",
    "natural features": "natural=*",
    "nature": "natural=*",
    "geographic feature": "natural=*",
    "geographic features": "natural=*",
    "landform": "natural=*",
    "landforms": "natural=*",
    # Waterways (wildcard - matches all waterway types)
    "waterway": "waterway=*",
    "waterways": "waterway=*",
    "water": "waterway=*",
    "river": "waterway=river",
    "rivers": "waterway=river",
    "stream": "waterway=stream",
    "streams": "waterway=stream",
    "canal": "waterway=canal",
    "canals": "waterway=canal",
    "drain": "waterway=drain",
    "drains": "waterway=drain",
    # Buildings (wildcard - matches all building types)
    "building": "building=*",
    "buildings": "building=*",
    "structure": "building=*",
    "structures": "building=*",
    "construction": "building=*",
    # Places (wildcard - matches all place types)
    "place": "place=*",
    "places": "place=*",
    "location": "place=*",
    "locations": "place=*",
    "settlement": "settlement=*",
    "settlements": "settlement=*",
    # Generic name search
    "name": "name=*",
    "named": "name=*",
    "named feature": "name=*",
    "named features": "name=*",
    # Boundaries and administrative areas
    "boundary": "boundary=*",
    "boundaries": "boundary=*",
    "border": "boundary=*",
    "borders": "boundary=*",
    "administrative": "boundary=administrative",
    "admin": "boundary=administrative",
    # Landuse (wildcard - matches all landuse types)
    "landuse": "landuse=*",
    "land use": "landuse=*",
    "area": "landuse=*",
    "zone": "landuse=*",
    "zones": "landuse=*",
    # Railway infrastructure
    "railway": "railway=*",
    "railways": "railway=*",
    "rail": "railway=*",
    # Generic highway/road/infrastructure queries (wildcard)
    "highway": "highway=*",
    "highways": "highway=*",
    "road": "highway=*",
    "roads": "highway=*",
    "street": "highway=*",
    "streets": "highway=*",
    "infrastructure": "highway=*",
    "transport infrastructure": "highway=*",
    "transportation": "highway=*",
    "route": "highway=*",
    "routes": "highway=*",
    # Generic military queries (wildcard)
    "military": "military=*",
    "defense": "military=*",
    "defence": "military=*",
    "military infrastructure": "military=*",
    "military facility": "military=*",
    "military facilities": "military=*",
    "military installation": "military=*",
    "military installations": "military=*",
    "armed forces": "military=*",
    "defense facility": "military=*",
    "defense facilities": "military=*",
    # Generic aeroway queries (wildcard)
    "aeroway": "aeroway=*",
    "aviation": "aeroway=*",
    "aviation infrastructure": "aeroway=*",
    "air transport": "aeroway=*",
}

# Geometry preferences for OSM keys
# Defines which geometry types (node, way, relation) should be included/excluded
# for different OSM tag keys to match user expectations
OSM_GEOMETRY_PREFERENCES = {
    "highway": {
        "preferred_geometries": ["way", "relation"],
        "exclude_geometries": ["node"],
        "exclude_values": {
            "bus_stop",
            "traffic_signals",
            "crossing",
            "stop",
            "give_way",
            "mini_roundabout",
            "motorway_junction",
        },
        "description": "Roads are linear features (ways), not point infrastructure",
    },
    "railway": {
        "preferred_geometries": ["way", "relation"],
        "exclude_geometries": ["node"],
        "exclude_values": {"station", "signal", "switch", "level_crossing"},
        "description": "Railway tracks are linear features, stations are points",
    },
    "waterway": {
        "preferred_geometries": ["way", "relation"],
        "exclude_geometries": ["node"],
        "exclude_values": {"weir", "lock", "dam", "waterfall"},
        "description": "Waterways are linear features (rivers, streams), not point features",
    },
    "aeroway": {
        "preferred_geometries": ["way", "relation"],
        "exclude_geometries": ["node"],
        "exclude_values": {"gate"},
        "description": "Aeroways are linear features (runways, taxiways), gates are points",
    },
    "power": {
        "preferred_geometries": ["way", "relation"],
        "exclude_geometries": ["node"],
        "exclude_values": {"tower", "pole", "substation", "generator"},
        "description": "Power lines are linear features, infrastructure is points",
    },
}
