# Dcumentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

# Weekly dependabot updates for Python (Poetry), Node.js (npm), and Docker dependencies
version: 2
updates:
  # Backend Python dependencies (Poetry)
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "fix"
      include: "scope"

  # Frontend Node.js dependencies (npm)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "fix"
      include: "scope"

  # Backend Docker container dependencies
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Frontend Docker container dependencies
  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Nginx Docker container dependencies
  - package-ecosystem: "docker"
    directory: "/nginx"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
