# .github/workflows/setup.yml
on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.11"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      python-version: ${{ inputs.python-version }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
      - run: |
          python -m pip install --upgrade pip
          pip install poetry
      - run: |
          poetry config virtualenvs.in-project true
          poetry install --no-interaction --no-ansi
