# .github/workflows/setup.yml
on:
  workflow_call:
    inputs:
      python-version:
        description: "Which Python version to use"
        required: false
        type: string
        default: "3.11"
      project-dir:
        description: "Where to find pyproject.toml"
        required: false
        type: string
        default: "backend"

jobs:
  setup:
    runs-on: ubuntu-latest

    # ← this makes *all* run: steps start in `backend/`
    defaults:
      run:
        working-directory: ${{ inputs.project-dir }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-interaction --no-ansi
